### ISSUE TITLE
error compiling gamedevframework on ArchLinux ARM with gcc-6.1.1 glibc-2.23-5

### ISSUE THREAD

**Issue by Popolon** [GamedevFramework/gf#4]
I'm not sure about the part of the system that could be related to this issue ? 

The system uses 
* gcc 6.1.1
* glibc 2.23-5

[alarm@alarm build]$ make
[  0%] Building CXX object library/CMakeFiles/gf0.dir/Range.cc.o
/home/alarm/misc/gf/library/Range.cc:31:19: error: duplicate explicit instantiation of 'struct gf::v1::Range<unsigned int>' [-fpermissive]
   template struct Range<std::size_t>;
                   ^~~~~~~~~~~~~~~~~~
make[2]: *** [library/CMakeFiles/gf0.dir/build.make:327: library/CMakeFiles/gf0.dir/Range.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:118: library/CMakeFiles/gf0.dir/all] Error 2
make: *** [Makefile:128: all] Error 2

**Comment by jube** [comment]
I think `size_t` is the same as `unsigned` on this architecture. Not easy to fix.

**Comment by Popolon** [comment]
Is there a test that I can made to confirm this ? I use ARMv7 (32 bits), I know that for example, default float format is float not double in QT tool-kit on this platform, and double on x86 and ARMv8 (64 bits).

This can be tested like with this on linux, for both ARM 32bit (v5/v6/v7 I suppose) and ARM 64bit  (found in libjpeg-turbo), probably a test for each case is better here. I could at least provide some test/debug on ARMv7, and very probably soon on ARMv8

#if defined __GNUC__ && (defined __arm__ || defined __aarch64__)

There is some explanation about difference in types on both platforms here:
http://malideveloper.arm.com/downloads/ARMv8_64_bit_migration.pdf

**Comment by jube** [comment]
You can try to compile something like:

```cxx
#include <iostream>
#include <type_traits>

int main() {
  std::cout << std::boolalpha;
  std::cout << std::is_same<unsigned, std::size_t>::value << '\n';
  return 0;
}
```

Compile with `gcc -std=c++11 file.cc`. If it prints `true`, then it's the same type.

I see two possible solutions for this bug:

- easy: remove the explicit instantiation for `std::size_t` (same for Vector, Rect, etc)
- difficult: make a check at build time with [CheckTypeSize](https://cmake.org/cmake/help/v3.0/module/CheckTypeSize.html)

I do not really like the preprocessor condition based on architecture because this error may happen on other architectures.

**Comment by Popolon** [comment]
Answered true. So that's the problem :(.

I didn't coded in C++ since long time and discover lot of evolutions since last time.

**Comment by Popolon** [comment]
gcc -o test_validation2 -std=c++11 -lstdc++ test_validation.cpp 
I needed to type this to compile it, using or not -std=c++11 give  the same result.

**Comment by jube** [comment]
OK. So I will remove the explicit instantiations with std::size_t. Anyway, they are not used in the library. Will come in the next push.
